### ISSUE TITLE
Update utilities.js to allow for separate distance units

### ISSUE THREAD

**Issue by jethridge13** [growwithgooglema/gwg-mbta#16]
Currently, the formulas for distance return in kilometers. Add in the ability to easily work with miles or meters. 

Originally part of #8

**Comment by AbdouSeck** [comment]
@jethridge13 are you done with this? If so, mind closing this issue?

**Comment by jethridge13** [comment]
@AbdouSeck Yep, just finished with it. I'll close it out.

**Comment by jethridge13** [comment]
My apologies. I must've missed a step before committing previously. I pulled before my last commit but must've missed something else. I have updated the `dev` branch and it is now completely ahead of `master`!

**Comment by AbdouSeck** [comment]
@jethridge13 yay! Thank you so much!
