### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by br3ndonland** [growwithgooglema/gwg-mbta#25]
# Improve search

## Current behavior

The app appears to be searching a limited subset of locations and location names, and only returns results when a single match is found. Many locations, including names of T stops, return errors.

Example search terms that return errors (based on the [GitHub Pages site](https://growwithgooglema.github.io/gwg-mbta/) running in Firefox on macOS):

- Boston public library
- Copley
- State house (redirects map to Kenya)
- Whole Foods Market

Example search terms that work:

- Broad institute
- Copley square
- Massachusetts state house
- MIT

## Suggested behavior

For practical utility, the app should allow flexibility in search terms, with behavior as close to the Google Maps apps as permitted by the Google Maps API.

**Comment by AbdouSeck** [comment]
I'm going to look into this.
