### ISSUE TITLE
Add location access

### ISSUE THREAD

**Issue by br3ndonland** [growwithgooglema/gwg-mbta#26]
# Add location access

## Current behavior

The map is currently centered on MIT by default, and returns results when a single search term match is found.

## Suggested behavior

The app would be more helpful if it could detect the user's location, and return results based on that location, without manual search.

Importantly, the app should use, but not require, location access. If location access is denied by the user, the user should still be able to search.

**Comment by AbdouSeck** [comment]
[`navigator.geolocation.getcurrentposition`](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition) has a really faulty API from my experiences with it, but I would entertain adding this to the `google-maps.js` script as the first way of obtaining geolocation information. If for some reason--either the user refused to grant permission to the app or something else)--we can't get the user's geolocation information, we have them search a place and the associated stops.
