### ISSUE TITLE
Make university table responsive

### ISSUE THREAD

**Issue by br3ndonland** [growwithgooglema/gwg-mbta#27]
# Make university table responsive

## Current behavior

The university rankings page shows a list of universities in the Boston area, and ranks them according to the ratio of wheelchair-accessible stops to total stops.

![screen-shot-2018-04-15-at-3 36 13-pm](https://user-images.githubusercontent.com/26674818/38818449-5dfc0b8e-4168-11e8-9d8e-a81acfdb5292.png)

The table requires scrolling on mobile devices (simulates iPhone 6S):

![screen-shot-2018-04-15-at-15 36 34-iphone-6s](https://user-images.githubusercontent.com/26674818/38818659-75560708-4168-11e8-93a4-70fd6ce0aa09.png)

## Suggested behavior

The address column could be removed on small viewports, to improve the experience on mobile devices.

**Comment by AbdouSeck** [comment]
@br3ndonland I can work on this, if you have not yet started working on it?

**Comment by br3ndonland** [comment]
Sure @AbdouSeck , I haven't done it yet.
